CONFIG = struct( ...
    'nc_file', '/Users/bblanton/ees/TDS/ERA5/global/uvp/2018/2018.global.nc', ...  % replace with extractor for any storm
    'track_file', fullfile('..', 'input', 'ibtracs.NA.list.v04r01.csv'), ...
    'storm_name', 'FLORENCE', ...
    'storm_year', 2018, ...
    'storm_start', datetime(2018,9, 10,0,0,0), ...
    'storm_end',   datetime(2018,9,12,0,0,0), ...
    'resolution', 0.25, ...    % unused
    'grid_half_size', 40, ...
    'output_half_size', 40, ...
    'filter_domain_size', 120, ...
    'num_radial_points', 1000, ...
    'num_azimuth_points', 360, ...
    'max_radius_deg', 10, ...
    'wind_threshold_10', 10, ...  % this is in m/s
    'wind_threshold_34', 34/1.944, ...
    'debug', true ...
);

