function storm = createOutputStruct(OUTPUT, time, real_lon, real_lat, era5_lon, era5_lat)

    output_lon = OUTPUT.lon - 360;
    real_lon = real_lon - 360;
    era5_lon = era5_lon - 360;
    mask = 1 - OUTPUT.mask;
    mask34 = 1 - OUTPUT.mask34;
    
    storm = struct( ...
        'Time', time, ...
        'Lo', output_lon, ...
        'La', OUTPUT.lat, ...
        'Vortex_mask', mask, ...
        'Vortex_mask34', mask34, ...
        'env_msl', OUTPUT.slp, ...
        'env_u10', OUTPUT.u, ...
        'env_v10', OUTPUT.v, ...
        'hur_msl', OUTPUT.dis_slp, ...
        'hur_u10', OUTPUT.dis_u, ...
        'hur_v10', OUTPUT.dis_v, ...
        'BestTrack_lon', real_lon, ...
        'BestTrack_lat', real_lat, ...
        'distance_10', OUTPUT.distance, ...
        'distance_34', OUTPUT.distance_34, ...
        'min_pressure_center_lon', era5_lon, ...
        'min_pressure_center_lat', era5_lat ...
    );
    
    varnames = ["env_msl", "env_u10", "env_v10", "hur_msl", "hur_u10", "hur_v10"];
    varunits = ["mb", "m/s", "m/s", "mb", "m/s", "m/s"];
    storm.units = dictionary(varnames, varunits);
end
