function OUTPUT = initializeOutputArrays(num, CONFIG)
    grid_size = 2 * CONFIG.output_half_size + 1;
    OUTPUT = struct( ...
        'lon', zeros(num, grid_size, grid_size), ...
        'lat', zeros(num, grid_size, grid_size), ...
        'slp', zeros(num, grid_size, grid_size), ...
        'u', zeros(num, grid_size, grid_size), ...
        'v', zeros(num, grid_size, grid_size), ...
        'dis_slp', zeros(num, grid_size, grid_size), ...
        'dis_u', zeros(num, grid_size, grid_size), ...
        'dis_v', zeros(num, grid_size, grid_size), ...
        'mask', zeros(num, grid_size, grid_size), ...
        'mask_inner', zeros(num, grid_size, grid_size), ...
        'distance_outer', zeros(num, 24), ...
        'distance_inner', zeros(num, 24) ...
    );
end
