%% === Basic Usage ===

nws13_combined_netcdf('Florence.sub1to3.nc', 'blended_output_times1to3.mat', 'test_Florence1to3.nc');

%% === Customized Usage ===

nws13_combined_netcdf('era5_data.nc', 'gahm_data.mat', 'combined_output.nc', ...
                      'Title', 'Hurricane Analysis Dataset', ...
                      'Institution', 'My University', ...
                      'MainGroupName', 'ERA5_Data', ...
                      'GAHMGroupName', 'Hurricane_Model');

%% === For different Variable Names ===

era5_vars = struct('lon', 'longitude', 'lat', 'latitude', 'time', 'time', ...
                   'u10', 'u_wind', 'v10', 'v_wind', 'msl', 'pressure');

gahm_vars = struct('fields_var', 'EVReggrid_out_times_1to3', ...
                          'grid_var', 'Reggrid_out_times_1to3');

nws13_combined_netcdf('era5_data.nc', 'gahm_data.mat', 'combined_output.nc', ...
                      'ERA5VarNames', era5_vars, 'GAHMVarNames', gahm_vars);