function OUTPUT = initializeOutputArrays(numTimes, CONFIG)
    grid_size = CONFIG.grid_size;
    output_radials = CONFIG.num_azimuthal_points;
    OUTPUT = struct( ...
        'lon', zeros(numTimes, grid_size, grid_size), ...
        'lat', zeros(numTimes, grid_size, grid_size), ...
        'slp', zeros(numTimes, grid_size, grid_size), ...
        'u', zeros(numTimes, grid_size, grid_size), ...
        'v', zeros(numTimes, grid_size, grid_size), ...
        'dis_slp', zeros(numTimes, grid_size, grid_size), ...
        'dis_u', zeros(numTimes, grid_size, grid_size), ...
        'dis_v', zeros(numTimes, grid_size, grid_size), ...
        'mask_outer', false(numTimes, grid_size, grid_size), ...
        'mask_inner', false(numTimes, grid_size, grid_size), ...
        'distance_outer', zeros(numTimes, output_radials), ...
        'distance_inner', zeros(numTimes, output_radials) ...
    );
end
