function OUTPUT = initializeOutputArrays(numTimes, CONFIG)
    grid_size = 2 * CONFIG.output_half_size + 1;
    OUTPUT = struct( ...
        'lon', zeros(numTimes, grid_size, grid_size), ...
        'lat', zeros(numTimes, grid_size, grid_size), ...
        'slp', zeros(numTimes, grid_size, grid_size), ...
        'u', zeros(numTimes, grid_size, grid_size), ...
        'v', zeros(numTimes, grid_size, grid_size), ...
        'dis_slp', zeros(numTimes, grid_size, grid_size), ...
        'dis_u', zeros(numTimes, grid_size, grid_size), ...
        'dis_v', zeros(numTimes, grid_size, grid_size), ...
        'mask', false(numTimes, grid_size, grid_size), ...
        'mask_inner', false(numTimes, grid_size, grid_size), ...
        'distance_outer', zeros(numTimes, 24), ...
        'distance_inner', zeros(numTimes, 24) ...
    );
end
