%--------------------------------------------------------------------------
% Compare current GAHM26 outputs against a saved baseline.
%
% This script re-runs the pipeline with the same configuration used to
% generate the baseline, then compares all key output fields. It reports
% maximum absolute and relative differences for each field and flags any
% that exceed specified tolerances.
%
% Usage:
%   cd into the GAHM26 directory, then run:
%     >> compare_to_baseline
%
% Tolerances:
%   velocity_tol  - m/s, absolute tolerance for VelU, VelV  (default 1e-10)
%   pressure_tol  - mb,  absolute tolerance for Press        (default 1e-10)
%   distance_tol  - m,   absolute tolerance for Rmax, RmaxQ  (default 1e-6)
%   parameter_tol -      absolute tolerance for B, Bg, phi    (default 1e-10)
%
% Requires:
%   tools/baseline_env1.mat and/or tools/baseline_env3.mat
%   (generated by generate_baseline.m)
%
%                    February 2026
%--------------------------------------------------------------------------

warning off

fprintf('\n=== GAHM26 Regression Comparison ===\n\n')

toolsdir = fileparts(mfilename('fullpath'));
projdir  = fileparts(toolsdir);

velocity_tol  = 1e-10;
pressure_tol  = 1e-10;
distance_tol  = 1e-6;
parameter_tol = 1e-10;

total_pass = 0;
total_fail = 0;

%% Common parameters (must match generate_baseline.m exactly)

storm_info.file_name   = fullfile(projdir, 'input', 'ibtracs.NA.list.v04r01.csv');
storm_info.file_type   = "IBTrACS";
storm_info.name        = 'FLORENCE';
storm_info.year        = '2018';
storm_info.designation = 'AL06';
storm_info.starttime   = '2018091312';
storm_info.endtime     = '2018091500';

GAHM_param_info.Vmax_multiplier    = 1;
GAHM_param_info.one2tenF           = 0.89;
GAHM_param_info.BLF                = 0.9;
GAHM_param_info.Bmin               = 0.5;
GAHM_param_info.Bmax               = 2.5;
GAHM_param_info.SVorMax_10_tblmin  = 20;
GAHM_param_info.SVorQuad_10_tblmin = 5;
GAHM_param_info.rhoa               = 1.204;
GAHM_param_info.pback_def          = 1013;
GAHM_param_info.version            = 3;
GAHM_param_info.Bg0M               = 1;
GAHM_param_info.c0                 = 0;

GAHM_compute_info.ntheta = 24;
GAHM_compute_info.nr     = 800;
GAHM_compute_info.delr   = 1000;

output_info.warnings       = fullfile(toolsdir, 'compare_warnings.dat');
output_info.NetCDFfilename = fullfile(toolsdir, 'compare_test');
output_info.timeinc        = 1;
output_info.type           = "grid";
output_info.nlon           = 51;
output_info.nlat           = 51;
output_info.dellon         = 0.1;
output_info.dellat         = 0.1;

%% Test 1: env_type = 1

baseline_file_1 = fullfile(toolsdir, 'baseline_env1.mat');
if exist(baseline_file_1, 'file')
    fprintf('--- Test 1: env_type=1 (ADCIRC/ASWIP) ---\n')

    env_info_1.type             = 1;
    env_info_1.taper_flag       = false;
    env_info_1.taper_mindelr2r1 = 0.1;
    env_info_1.taper_a          = 2;

    WAF_info_1.flag = false;

    S = load(baseline_file_1, 'baseline');
    bl = S.baseline;
    fprintf('  Baseline generated: %s\n', char(bl.generated));

    try
        tic;
        [Reggrid_out, Reggrid_TC_out, Reggrid_Env_out, Reggrid_VVor_invtapHur_out, ...
            Trackdata, GAHM_out] = GAHM2026(storm_info, GAHM_param_info, ...
            GAHM_compute_info, WAF_info_1, env_info_1, output_info);
        elapsed = toc;
        fprintf('  Run completed in %.1f seconds\n', elapsed);

        [p, f] = compare_all_fields(bl, Reggrid_out, Reggrid_TC_out, ...
                     Reggrid_Env_out, GAHM_out, Trackdata, ...
                     velocity_tol, pressure_tol, distance_tol, parameter_tol);
        total_pass = total_pass + p;
        total_fail = total_fail + f;
    catch ME
        fprintf('  RUN FAILED: %s\n', ME.message);
        total_fail = total_fail + 1;
    end
else
    fprintf('--- Test 1: SKIPPED (baseline_env1.mat not found) ---\n')
    fprintf('  Run generate_baseline.m first.\n')
end

%% Test 2: env_type = 3

baseline_file_3 = fullfile(toolsdir, 'baseline_env3.mat');
if exist(baseline_file_3, 'file')
    fprintf('\n--- Test 2: env_type=3 (gridded env + taper + WAF) ---\n')

    env_info_3.type             = 3;
    env_info_3.file_name        = 'Florence';
    env_info_3.taper_flag       = true;
    env_info_3.taper_mindelr2r1 = 0.1;
    env_info_3.taper_a          = 2;

    S = load(baseline_file_3, 'baseline');
    bl = S.baseline;
    fprintf('  Baseline generated: %s\n', char(bl.generated));

    WAF_info_3.flag = false;
    if isfield(bl.config, 'WAF_flag') && bl.config.WAF_flag
        waf_file = fullfile(projdir, 'WAF_15deg_10km_6km_raster_test.tif');
        if exist(waf_file, 'file')
            WAF_info_3.flag      = true;
            WAF_info_3.file_name = waf_file;
        else
            fprintf('  WARNING: baseline used WAF but raster not found\n');
        end
    end

    try
        tic;
        [Reggrid_out, Reggrid_TC_out, Reggrid_Env_out, Reggrid_VVor_invtapHur_out, ...
            Trackdata, GAHM_out] = GAHM2026(storm_info, GAHM_param_info, ...
            GAHM_compute_info, WAF_info_3, env_info_3, output_info);
        elapsed = toc;
        fprintf('  Run completed in %.1f seconds\n', elapsed);

        [p, f] = compare_all_fields(bl, Reggrid_out, Reggrid_TC_out, ...
                     Reggrid_Env_out, GAHM_out, Trackdata, ...
                     velocity_tol, pressure_tol, distance_tol, parameter_tol);
        total_pass = total_pass + p;
        total_fail = total_fail + f;
    catch ME
        fprintf('  RUN FAILED: %s\n', ME.message);
        total_fail = total_fail + 1;
    end
else
    fprintf('\n--- Test 2: SKIPPED (baseline_env3.mat not found) ---\n')
end

%% Test 3: Full Florence case (351x351 grid, WAF, env_type=3)

baseline_file_florence = fullfile(toolsdir, 'baseline_florence.mat');
if exist(baseline_file_florence, 'file')
    fprintf('\n--- Test 3: Full Florence (351x351 grid, WAF, env_type=3) ---\n')

    env_info_full.type             = 3;
    env_info_full.file_name        = 'Florence';
    env_info_full.taper_flag       = true;
    env_info_full.taper_mindelr2r1 = 0.1;
    env_info_full.taper_a          = 2;

    S = load(baseline_file_florence, 'baseline');
    bl = S.baseline;
    fprintf('  Baseline generated: %s\n', char(bl.generated));

    WAF_info_full.flag = false;
    if isfield(bl.config, 'WAF_flag') && bl.config.WAF_flag
        waf_file = fullfile(projdir, 'WAF_15deg_10km_6km_raster_test.tif');
        if exist(waf_file, 'file')
            WAF_info_full.flag      = true;
            WAF_info_full.file_name = waf_file;
        else
            fprintf('  WARNING: baseline used WAF but raster not found\n');
        end
    end

    output_info_full.warnings       = fullfile(toolsdir, 'compare_florence_warnings.dat');
    output_info_full.NetCDFfilename = fullfile(toolsdir, 'compare_florence');
    output_info_full.timeinc        = 1;
    output_info_full.type           = "grid";
    output_info_full.nlon           = bl.config.nlon;
    output_info_full.nlat           = bl.config.nlat;
    output_info_full.dellon         = bl.config.dellon;
    output_info_full.dellat         = bl.config.dellat;

    try
        tic;
        [Reggrid_out, Reggrid_TC_out, Reggrid_Env_out, Reggrid_VVor_invtapHur_out, ...
            Trackdata, GAHM_out] = GAHM2026(storm_info, GAHM_param_info, ...
            GAHM_compute_info, WAF_info_full, env_info_full, output_info_full);
        elapsed = toc;
        fprintf('  Run completed in %.1f seconds\n', elapsed);

        [p, f] = compare_all_fields(bl, Reggrid_out, Reggrid_TC_out, ...
                     Reggrid_Env_out, GAHM_out, Trackdata, ...
                     velocity_tol, pressure_tol, distance_tol, parameter_tol);
        total_pass = total_pass + p;
        total_fail = total_fail + f;
    catch ME
        fprintf('  RUN FAILED: %s\n', ME.message);
        total_fail = total_fail + 1;
    end
else
    fprintf('\n--- Test 3: SKIPPED (baseline_florence.mat not found) ---\n')
end

%% Summary

fprintf('\n=== SUMMARY ===\n')
fprintf('  PASS: %d\n', total_pass);
fprintf('  FAIL: %d\n', total_fail);
if total_fail == 0 && total_pass > 0
    fprintf('  Result: ALL CHECKS PASSED\n')
elseif total_fail > 0
    fprintf('  Result: REGRESSION DETECTED\n')
else
    fprintf('  Result: NO BASELINES FOUND - run generate_baseline.m first\n')
end
fprintf('\n')


%% ========================================================================
%  Helper functions
%  ========================================================================

function [npass, nfail] = compare_all_fields(bl, Reggrid_out, Reggrid_TC_out, ...
                              Reggrid_Env_out, GAHM_out, Trackdata, ...
                              vel_tol, press_tol, dist_tol, param_tol)

    npass = 0;
    nfail = 0;

    % Check timestep counts
    nt = length(Reggrid_out);
    if nt ~= bl.nt
        fprintf('  FAIL: timestep count mismatch (baseline=%d, current=%d)\n', bl.nt, nt);
        nfail = nfail + 1;
        return
    end
    fprintf('  Timesteps: %d (match)\n', nt);

    % --- TC output fields ---
    fprintf('  Gridded TC output:\n');
    [p, f] = compare_cell_field(bl.TC_VelU, Reggrid_TC_out, 'VelU', 'TC_VelU', vel_tol);
    npass = npass + p; nfail = nfail + f;

    [p, f] = compare_cell_field(bl.TC_VelV, Reggrid_TC_out, 'VelV', 'TC_VelV', vel_tol);
    npass = npass + p; nfail = nfail + f;

    [p, f] = compare_cell_field(bl.TC_Press, Reggrid_TC_out, 'Press', 'TC_Press', press_tol);
    npass = npass + p; nfail = nfail + f;

    % --- Env output fields ---
    if isfield(bl, 'Env_VelU') && isstruct(Reggrid_Env_out) && ...
       isfield(Reggrid_Env_out, 'VelU')
        fprintf('  Gridded Env output:\n');
        [p, f] = compare_cell_field(bl.Env_VelU, Reggrid_Env_out, 'VelU', 'Env_VelU', vel_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_field(bl.Env_VelV, Reggrid_Env_out, 'VelV', 'Env_VelV', vel_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_field(bl.Env_Press, Reggrid_Env_out, 'Press', 'Env_Press', press_tol);
        npass = npass + p; nfail = nfail + f;
    end

    % --- GAHM parameter fields ---
    nt_gahm = length(GAHM_out);
    if nt_gahm ~= bl.nt_gahm
        fprintf('  FAIL: GAHM timestep count mismatch (baseline=%d, current=%d)\n', bl.nt_gahm, nt_gahm);
        nfail = nfail + 1;
    else
        fprintf('  GAHM parameters (%d track times):\n', nt_gahm);

        [p, f] = compare_vector(bl.GAHM_B, [GAHM_out.B], 'GAHM.B', param_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_vector(bl.GAHM_Rmax_in, [GAHM_out.Rmax_in], 'GAHM.Rmax_in', dist_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_vector(bl.GAHM_Rmax_tot, [GAHM_out.Rmax_tot], 'GAHM.Rmax_tot', dist_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_vector(bl.GAHM_SVorMax, [GAHM_out.SVorMax_10_10], 'GAHM.SVorMax', vel_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_array(bl.GAHM_Rmax, {GAHM_out.Rmax}, 'GAHM.Rmax', dist_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_array(bl.GAHM_Bg, {GAHM_out.Bg}, 'GAHM.Bg', param_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_array(bl.GAHM_phi, {GAHM_out.phi}, 'GAHM.phi', param_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_array(bl.GAHM_RmaxQ, {GAHM_out.RmaxQ}, 'GAHM.RmaxQ', dist_tol);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_cell_array(bl.GAHM_flag, {GAHM_out.flag}, 'GAHM.flag', 0);
        npass = npass + p; nfail = nfail + f;
    end

    % --- Track data ---
    nt_track = length(Trackdata);
    if nt_track ~= bl.nt_track
        fprintf('  FAIL: Track timestep count mismatch (baseline=%d, current=%d)\n', bl.nt_track, nt_track);
        nfail = nfail + 1;
    else
        fprintf('  Track data (%d output times):\n', nt_track);
        [p, f] = compare_vector(bl.Track_Lat, [Trackdata.Lat], 'Track.Lat', 1e-12);
        npass = npass + p; nfail = nfail + f;

        [p, f] = compare_vector(bl.Track_Lon, [Trackdata.Lon], 'Track.Lon', 1e-12);
        npass = npass + p; nfail = nfail + f;
    end
end


function [npass, nfail] = compare_cell_field(bl_cells, struct_array, fieldname, label, tol)
    npass = 0;
    nfail = 0;
    max_abs_diff = 0;
    max_rel_diff = 0;
    for i = 1:length(bl_cells)
        bl_data  = bl_cells{i};
        cur_data = struct_array(i).(fieldname);
        if ~isequal(size(bl_data), size(cur_data))
            fprintf('    FAIL: %s size mismatch at t=%d\n', label, i);
            nfail = nfail + 1;
            return
        end
        both_nan = isnan(bl_data) & isnan(cur_data);
        bl_only_nan = isnan(bl_data) & ~isnan(cur_data);
        cur_only_nan = ~isnan(bl_data) & isnan(cur_data);
        if any(bl_only_nan(:)) || any(cur_only_nan(:))
            fprintf('    FAIL: %s NaN pattern mismatch at t=%d\n', label, i);
            nfail = nfail + 1;
            return
        end
        valid = ~both_nan;
        if any(valid(:))
            adiff = abs(bl_data(valid) - cur_data(valid));
            max_abs_diff = max(max_abs_diff, max(adiff(:)));
            denom = max(abs(bl_data(valid)), 1e-15);
            rdiff = adiff ./ denom;
            max_rel_diff = max(max_rel_diff, max(rdiff(:)));
        end
    end
    if max_abs_diff <= tol
        fprintf('    PASS: %-20s max_abs=%.2e  max_rel=%.2e\n', label, max_abs_diff, max_rel_diff);
        npass = 1;
    else
        fprintf('    FAIL: %-20s max_abs=%.2e  max_rel=%.2e  (tol=%.2e)\n', label, max_abs_diff, max_rel_diff, tol);
        nfail = 1;
    end
end


function [npass, nfail] = compare_vector(bl_vec, cur_vec, label, tol)
    npass = 0;
    nfail = 0;
    if length(bl_vec) ~= length(cur_vec)
        fprintf('    FAIL: %s length mismatch (baseline=%d, current=%d)\n', label, length(bl_vec), length(cur_vec));
        nfail = 1;
        return
    end
    both_nan = isnan(bl_vec) & isnan(cur_vec);
    bl_only_nan = isnan(bl_vec) & ~isnan(cur_vec);
    cur_only_nan = ~isnan(bl_vec) & isnan(cur_vec);
    if any(bl_only_nan) || any(cur_only_nan)
        fprintf('    FAIL: %s NaN pattern mismatch\n', label);
        nfail = 1;
        return
    end
    valid = ~both_nan;
    if any(valid)
        adiff = abs(bl_vec(valid) - cur_vec(valid));
        max_abs = max(adiff);
        denom = max(abs(bl_vec(valid)), 1e-15);
        max_rel = max(adiff ./ denom);
    else
        max_abs = 0;
        max_rel = 0;
    end
    if max_abs <= tol
        fprintf('    PASS: %-20s max_abs=%.2e  max_rel=%.2e\n', label, max_abs, max_rel);
        npass = 1;
    else
        fprintf('    FAIL: %-20s max_abs=%.2e  max_rel=%.2e  (tol=%.2e)\n', label, max_abs, max_rel, tol);
        nfail = 1;
    end
end


function [npass, nfail] = compare_cell_array(bl_cells, cur_cells, label, tol)
    npass = 0;
    nfail = 0;
    max_abs_diff = 0;
    max_rel_diff = 0;
    if length(bl_cells) ~= length(cur_cells)
        fprintf('    FAIL: %s count mismatch\n', label);
        nfail = 1;
        return
    end
    for i = 1:length(bl_cells)
        bl_data  = bl_cells{i};
        cur_data = cur_cells{i};
        if ~isequal(size(bl_data), size(cur_data))
            fprintf('    FAIL: %s size mismatch at t=%d\n', label, i);
            nfail = 1;
            return
        end
        both_nan = isnan(bl_data) & isnan(cur_data);
        bl_only_nan = isnan(bl_data) & ~isnan(cur_data);
        cur_only_nan = ~isnan(bl_data) & isnan(cur_data);
        if any(bl_only_nan(:)) || any(cur_only_nan(:))
            fprintf('    FAIL: %s NaN pattern mismatch at t=%d\n', label, i);
            nfail = 1;
            return
        end
        valid = ~both_nan;
        if any(valid(:))
            adiff = abs(bl_data(valid) - cur_data(valid));
            max_abs_diff = max(max_abs_diff, max(adiff(:)));
            denom = max(abs(bl_data(valid)), 1e-15);
            rdiff = adiff ./ denom;
            max_rel_diff = max(max_rel_diff, max(rdiff(:)));
        end
    end
    if max_abs_diff <= tol
        fprintf('    PASS: %-20s max_abs=%.2e  max_rel=%.2e\n', label, max_abs_diff, max_rel_diff);
        npass = 1;
    else
        fprintf('    FAIL: %-20s max_abs=%.2e  max_rel=%.2e  (tol=%.2e)\n', label, max_abs_diff, max_rel_diff, tol);
        nfail = 1;
    end
end
