function success = run_tests()
% run_tests  Run GAHM2026 regression tests and return pass/fail status.
%
%   success = run_tests() runs the compare_to_baseline regression suite
%   and returns true if all tests pass, false otherwise. Throws an error
%   if any tests fail, so that MATLAB exits with non-zero status when
%   invoked via the -batch flag.
%
%   Requires baseline files generated by generate_baseline.m
%   (e.g., tools/baseline_env1.mat, tools/baseline_env3.mat).
%
%   Example CI usage:
%     matlab -batch "addpath('tools'); run_tests"

    toolsdir = fileparts(mfilename('fullpath'));
    projdir  = fileparts(toolsdir);
    addpath(projdir)
    addpath(fullfile(projdir, 'util'))
    addpath(fullfile(projdir, 'SeparateEnvHur'))

    compare_to_baseline

    success = (total_fail == 0 && total_pass > 0);

    if ~success
        error("run_tests:testFailure", ...
            "Regression tests failed: %d checks failed, %d passed.", ...
            total_fail, total_pass);
    end
end
