source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-seo-tag", "~> 2.8"
gem "just-the-docs", "~> 0.10"

group :jekyll_plugins do
  gem "webrick", "~> 1.8"
end
